# Generated by Django 4.2.9 on 2024-05-17 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('common_name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Wildlife Class',
                'verbose_name_plural': 'Wildlife Classes',
            },
        ),
        migrations.CreateModel(
            name='WildlifeFamiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('common_name', models.CharField(db_index=True, max_length=255)),
                ('familyrank', models.CharField(max_length=255)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='wildlifeAPI.wildlifeclasses')),
            ],
            options={
                'verbose_name': 'Wildlife Family',
                'verbose_name_plural': 'Wildlife Families',
            },
        ),
        migrations.CreateModel(
            name='WildlifeKingdoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('common_name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Wildlife Kingdom',
                'verbose_name_plural': 'Wildlife Kingdoms',
            },
        ),
        migrations.CreateModel(
            name='WildlifeSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('common_name', models.CharField(db_index=True, max_length=255)),
                ('taxonid', models.CharField(max_length=255)),
                ('endemicity', models.CharField(max_length=255)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='wildlifeAPI.wildlifeclasses')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='wildlifeAPI.wildlifefamiles')),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='wildlifeAPI.wildlifekingdoms')),
            ],
            options={
                'verbose_name': 'Wildlife Species',
                'verbose_name_plural': 'Wildlife Species',
            },
        ),
        migrations.CreateModel(
            name='WildlifeSpeciesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='wildlifeAPI.wildlifespecies')),
            ],
            options={
                'verbose_name': 'Wildlife Species Information',
                'verbose_name_plural': 'Wildlife Species Information',
            },
        ),
        migrations.CreateModel(
            name='WildlifeSpeciesInfoField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='wildlifeAPI.wildlifespeciesinfo')),
            ],
            options={
                'verbose_name': 'Wildlife Species Information Field',
                'verbose_name_plural': 'Wildlife Species Information Fields',
            },
        ),
        migrations.AddField(
            model_name='wildlifefamiles',
            name='kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='wildlifeAPI.wildlifekingdoms'),
        ),
        migrations.AddField(
            model_name='wildlifeclasses',
            name='kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='wildlifeAPI.wildlifekingdoms'),
        ),
    ]
