# Generated by Django 4.2.9 on 2024-05-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifeAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WildlifeFamiles',
            new_name='WildlifeFamilies',
        ),
    ]
