# Generated by Django 4.2.9 on 2024-05-18 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifeAPI', '0003_alter_wildlifeclasses_kingdom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlifeclasses',
            name='kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='wildlifeAPI.wildlifekingdoms'),
        ),
        migrations.AlterField(
            model_name='wildlifefamilies',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='wildlifeAPI.wildlifeclasses'),
        ),
        migrations.AlterField(
            model_name='wildlifefamilies',
            name='kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='wildlifeAPI.wildlifekingdoms'),
        ),
        migrations.AlterField(
            model_name='wildlifespecies',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='wildlifeAPI.wildlifeclasses'),
        ),
        migrations.AlterField(
            model_name='wildlifespecies',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='wildlifeAPI.wildlifefamilies'),
        ),
        migrations.AlterField(
            model_name='wildlifespecies',
            name='kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='wildlifeAPI.wildlifekingdoms'),
        ),
        migrations.AlterField(
            model_name='wildlifespeciesinfo',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='wildlifeAPI.wildlifespecies'),
        ),
        migrations.AlterField(
            model_name='wildlifespeciesinfofield',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='wildlifeAPI.wildlifespeciesinfo'),
        ),
    ]
