# Generated by Django 4.2.9 on 2024-05-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifeAPI', '0004_alter_wildlifeclasses_kingdom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeSpeciesConservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nca_status', models.CharField(max_length=255, null=True)),
                ('nca_status_code', models.CharField(max_length=1, null=True)),
                ('conservation_significant', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WildlifeSpeciesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
                ('format', models.CharField(max_length=255, null=True)),
                ('url', models.URLField(null=True)),
                ('reference', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wildlifespecies',
            name='endemicity',
        ),
        migrations.AddField(
            model_name='wildlifespeciesinfo',
            name='endemicity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wildlifespeciesinfo',
            name='environment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wildlifespeciesinfo',
            name='isSuperseded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wildlifespeciesinfo',
            name='pest_status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wildlifespeciesinfo',
            name='synonyms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wildlifespeciesinfo',
            name='wetland_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='WildlifeSpeciesInfoField',
        ),
        migrations.AddField(
            model_name='wildlifespeciesimage',
            name='species',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='wildlifeAPI.wildlifespecies'),
        ),
        migrations.AddField(
            model_name='wildlifespeciesconservationstatus',
            name='species',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conservation_status', to='wildlifeAPI.wildlifespecies'),
        ),
        migrations.AddField(
            model_name='wildlifespeciesinfo',
            name='conservation_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='wildlifeAPI.wildlifespeciesconservationstatus'),
        ),
        migrations.AddField(
            model_name='wildlifespeciesinfo',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='wildlifeAPI.wildlifespeciesimage'),
        ),
    ]
