# Generated by Django 4.2.9 on 2024-05-19 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifeAPI', '0005_wildlifespeciesconservationstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlifespeciesinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='wildlifespeciesinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wildlifespeciesimage',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='wildlifeAPI.wildlifespecies'),
        ),
    ]
