# Generated by Django 4.2.9 on 2024-05-21 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifeAPI', '0006_remove_wildlifespeciesinfo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifeclasses',
            name='kingdom_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wildlifefamilies',
            name='_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='families', to='wildlifeAPI.wildlifeclasses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wildlifefamilies',
            name='kingdom_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wildlifespecies',
            name='_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='wildlifeAPI.wildlifeclasses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wildlifespecies',
            name='family_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wildlifespecies',
            name='kingdom_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wildlifespeciesconservationstatus',
            name='species_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wildlifespeciesimage',
            name='species_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wildlifefamilies',
            name='class_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wildlifespecies',
            name='class_name',
            field=models.CharField(max_length=255),
        ),
    ]
