# Generated by Django 4.2.9 on 2024-05-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifeAPI', '0007_wildlifeclasses_kingdom_name_wildlifefamilies__class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifespeciesinfo',
            name='species_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
