# Generated by Django 3.2.25 on 2024-06-02 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_followers'),
        ('wildlifeAPI', '0008_wildlifespeciesinfo_species_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeSpeciesSightings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='wildlifeAPI.wildlifespecies')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='users.profile')),
            ],
        ),
    ]
