# Generated by Django 3.2.25 on 2024-05-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routes',
            options={'verbose_name': 'Routes', 'verbose_name_plural': 'User Routes'},
        ),
        migrations.AlterModelTable(
            name='routes',
            table='routes',
        ),
    ]
