# Generated by Django 3.2.25 on 2024-05-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20240529_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routes',
            old_name='time',
            new_name='time_spent',
        ),
    ]
