# Generated by Django 3.2.25 on 2024-05-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_rename_time_routes_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='method',
            field=models.CharField(default='GET', max_length=10),
        ),
    ]
