# Generated by Django 3.2.25 on 2024-05-29 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0004_routes_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='ip_address',
            field=models.GenericIPAddressField(default='127:0:0:1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
