# Generated by Django 3.2.25 on 2024-05-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20240529_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
