# Generated by Django 3.2.25 on 2024-05-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_alter_routes_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocationlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
