# Generated by Django 4.2.9 on 2024-05-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_city_profile_country_profile_zip_code'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
