# Generated by Django 4.2.9 on 2024-05-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
